### ISSUE TITLE
Help Required in running md2csv.

### ISSUE THREAD

**Issue by rameezrehman408** [digitorus/md2csv#1]
Hi @vanbroup
I need help/guidance in running this code.
I am running the docker container as shown below:
![image](https://github.com/user-attachments/assets/3cc3fc86-60dc-4687-bd15-d219156e5377)

Trying to convert the Code Signing Baseline Requirement  into its .csv file.

Can you please tell me what I am doing wrong here?

PS: I was experimenting with eramba and was manually translating the WebTrust Requirements and CAB Forum Requirements to the eramba's [Compliance Package](https://www.eramba.org/learning/courses/9/episodes/203). Found upon this tool of yours and wanted to utilize it.
In case, I am on the wrong path, could you guide me there as well? 
Best Regards,
Rameez.

**Comment by rameezrehman408** [comment]
@vanbroup 
I was able to run the command as follows:
![image](https://github.com/user-attachments/assets/2029998a-0b67-4ba8-9f01-9dbad870b0de)

My sincerest apologies for a beginner mistake.

**Comment by vanbroup** [comment]
Hope it's useful, let me know if you run into any issues.
